[package]
name = "headwind-tw-index"
version = "0.1.0"
edition = "2021"

[dependencies]
headwind-core = { path = "../core" }
headwind-tw-parse = { path = "../tw_parse" }
serde = { workspace = true }
serde_json = { workspace = true }
